### ISSUE TITLE
[bug]: include_tag does not work

### ISSUE THREAD

**Issue by nonsonogio** [DariuszPorowski/mkdocs-file-filter-plugin#198]
### 🐛 What happened?

Pages are not excluded when include_tag is used - apparently only exclude_tag works

### 🔬 How to reproduce?

Configure as such:

```
theme:
  name: material

plugins:
  - file-filter:
      filter_nav: false
      metadata_property: visibility
      include_tag:
        - public

  - search
  - awesome-pages
  - ezlinks
  - tags:
      tags_file: tags.md
```

Create a page with this frontmatter:

```
visibility: public
```

The page will still be included in the build website.

### 🌌 Environment (plugin version)

0.2.0

### 🌌 Environment (OS)

Linux

### 🌌 Environment (Python)

3.11.1

### 🌌 Environment (MkDocs)

1.5.3

### 📈 Expected behavior

Error 404 when trying to access the "private" page i.e. any page WITHOUT the `visibility:public` in the frontmatter

### 📜 Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
